services:
  # =====================
  # Auth Service Database
  # =====================
  auth-db:
    image: mysql:8.0
    container_name: auth-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: authdb
      MYSQL_USER: authuser
      MYSQL_PASSWORD: authpass
    ports:
      - "3307:3306"   # external port to avoid clash with other MySQLs
    volumes:
      - auth-db-data:/var/lib/mysql
    networks:
      - expense-net

  # =====================
  # Money database
  # =====================
  money-db:
    image: mysql:8.0
    container_name: money-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: moneydb
      MYSQL_USER: moneyuser
      MYSQL_PASSWORD: moneypass
    ports:
      - "3308:3306"   # external port to avoid clash with other MySQLs
    volumes:
      - money-db-data:/var/lib/mysql
    networks:
      - expense-net
volumes:
 auth-db-data:
 money-db-data:

networks:
  expense-net:
    driver: bridge
